version: "3.5"
services:
  app: 
    image: node:14-alpine
    container_name: react-app
    volumes: 
      - ./:/app
    working_dir: /app
    ports:
      - 5173:5173
    command: npm start
    tty: true
